name: Continuous Delivery

on:
  push:
    tags:
      - "*.*.*"
    
jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      checks: write
      statuses: write
      actions: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup dotnet 6
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "6"

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: "6.x"
          
      - name: Determine GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4
        with:
          configFilePath: GitVersion.yml

      - name: Print version
        run: |
          echo "GITVERSION_FULLSEMVER=${{ steps.gitversion.outputs.FullSemVer }}" >> $GITHUB_ENV
          echo "GITVERSION_SEMVER=${{ steps.gitversion.outputs.SemVer }}" >> $GITHUB_ENV
          echo "GITVERSION_ASSEMBLYSEMVER=${{ steps.gitversion.outputs.assemblySemVer }}" >> $GITHUB_ENV

      - name: Verify tag version
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          EXPECTED="${GITHUB_REF_NAME#v}"
          ACTUAL="${GITVERSION_SEMVER}"

          echo "Actual version: $ACTUAL"
          echo "Expected version: $EXPECTED"

          if [ "$EXPECTED" != "$ACTUAL" ]; then
            echo "Tag version ($EXPECTED) does not match GitVersion ($ACTUAL)"
            exit 1
          fi

      - name: Build & publish (v6)
        run: dotnet publish --configuration Release -o publish -r win-x64 -p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Install Velopack CLI
        run: |
          dotnet tool install -g vpk

      - name: Download previous release for delta generation
        run: |
          vpk download github --repoUrl https://github.com/${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create Velopack package with deltas
        run: |
          vpk pack -u QuestLog -v ${{ github.ref_name }} -p publish

      - name: Create Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create "${{ github.ref_name }}"
          --repo "${{ github.event.repository.full_name }}"
          --title "${{ github.ref_name }}"
          --verify-tag
          --generate-notes

      - name: Upload Velopack package to release
        run: >
          vpk upload github --repoUrl https://github.com/${{ github.repository }} --tag ${{ github.ref_name }} --publish --token ${{ secrets.GITHUB_TOKEN }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    


