name: Continuous Integration

on:
  push:
    branches:
      - 'master'
      - 'development'
      - 'feature/**'
      - 'fix/**'
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.axaml'
  pull_request:
    branches:
      - 'master'
      - 'development'
      - 'feature/**'
      - 'fix/**'
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.axaml'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: "6"

    - name: Run linter
      run: dotnet format --verify-no-changes QuestLog.slnx

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
          versionSpec: "6.x"
          
    - name: Determine GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4
      with:
        configFilePath: GitVersion.yml

    - name: Print version
      run: |
        echo "GITVERSION_FULLSEMVER=${{ steps.gitversion.outputs.FullSemVer }}" >> $GITHUB_ENV
        echo "GITVERSION_SEMVER=${{ steps.gitversion.outputs.SemVer }}" >> $GITHUB_ENV
        echo "GITVERSION_ASSEMBLYSEMVER=${{ steps.gitversion.outputs.assemblySemVer }}" >> $GITHUB_ENV

    - name: Verify tag version
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: |
        EXPECTED="${GITHUB_REF_NAME#v}"
        ACTUAL="${GITVERSION_SEMVER}"

        echo "Actual version: $ACTUAL"
        echo "Expected version: $EXPECTED"

        if [ "$EXPECTED" != "$ACTUAL" ]; then
          echo "Tag version ($EXPECTED) does not match GitVersion ($ACTUAL)"
          exit 1
        fi

    - name: Restore dependencies
      run: dotnet restore QuestLog.slnx

    - name: Build .NET 6
      run: dotnet build QuestLog.slnx --no-restore --configuration Release -p:Version=${{ steps.gitversion.outputs.semVer }}
